ALTER TABLE tb_vendedor ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tb_forma_pagamento ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;


ALTER TABLE tb_venda ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tb_item_venda ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tb_lancamento_financeiro ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;